import { elevation, iconSizes, motion, radius, spacing, typography } from './tokens';

const shared = {
  spacing,
  radius,
  typography,
  elevation,
  iconSizes,
  motion,
};

export const themes = {
  botanicalLight: {
    id: 'botanicalLight',
    name: 'Botanical',
    mode: 'light',
    ...shared,
    colors: {
      background: '#FAF9F5',
      surface: '#FFFFFF',
      surfaceSoft: '#F4F4F0',
      surfaceHigh: '#E8E8E4',
      statSurface: '#FFFFFF',
      waterSurface: '#E3F2FD',
      fertilizerSurface: '#F1ECE9',
      harvestSurface: '#FFF1DD',
      successSurface: '#EAF7EC',
      errorSurface: '#FFE8E8',
      text: '#1A1C1A',
      textMuted: '#5B6558',
      primary: '#2E7D32',
      primaryStrong: '#0D631B',
      onPrimary: '#FFFFFF',
      secondary: '#81C784',
      secondaryContainer: '#ABF4AC',
      brown: '#795548',
      beige: '#F5F0E6',
      water: '#1976D2',
      sun: '#F6B73C',
      harvest: '#EF7D22',
      success: '#2E7D32',
      warning: '#B26A00',
      error: '#BA1A1A',
      info: '#1976D2',
      border: '#DCE3D7',
      shadow: '#0D631B',
    },
  },
  botanicalDark: {
    id: 'botanicalDark',
    name: 'Botanical',
    mode: 'dark',
    ...shared,
    colors: {
      background: '#111411',
      surface: '#191D19',
      surfaceSoft: '#202520',
      surfaceHigh: '#2A302A',
      statSurface: '#171C18',
      waterSurface: '#172331',
      fertilizerSurface: '#261F1B',
      harvestSurface: '#2A2117',
      successSurface: '#182419',
      errorSurface: '#2A1B1B',
      text: '#F0F3EC',
      textMuted: '#B8C0B3',
      primary: '#7EDC82',
      primaryStrong: '#9EE8A1',
      onPrimary: '#06210A',
      secondary: '#A4C3A0',
      secondaryContainer: '#2C5F34',
      brown: '#D1B0A0',
      beige: '#2A251E',
      water: '#8AB8FF',
      sun: '#FFD166',
      harvest: '#FFB36D',
      success: '#7EDC82',
      warning: '#FFD166',
      error: '#FFB4AB',
      info: '#8AB8FF',
      border: '#343B34',
      shadow: '#000000',
    },
  },
  harvestLight: {
    id: 'harvestLight',
    name: 'Harvest',
    mode: 'light',
    ...shared,
    colors: {
      background: '#FFF9F0',
      surface: '#FFFFFF',
      surfaceSoft: '#F8EFE2',
      surfaceHigh: '#F0DEC7',
      statSurface: '#FFFFFF',
      waterSurface: '#E5F2FB',
      fertilizerSurface: '#F3E8DC',
      harvestSurface: '#FFF0D8',
      successSurface: '#EAF5E4',
      errorSurface: '#FFE8E4',
      text: '#241A12',
      textMuted: '#6B5A4A',
      primary: '#3F7D3A',
      primaryStrong: '#275D28',
      onPrimary: '#FFFFFF',
      secondary: '#C7A35A',
      secondaryContainer: '#E5D8A8',
      brown: '#8A5A32',
      beige: '#F7E8CF',
      water: '#2F80B7',
      sun: '#E7A923',
      harvest: '#D9681F',
      success: '#3F7D3A',
      warning: '#A86200',
      error: '#B3261E',
      info: '#2F80B7',
      border: '#E6D4BC',
      shadow: '#8A5A32',
    },
  },
  harvestDark: {
    id: 'harvestDark',
    name: 'Harvest',
    mode: 'dark',
    ...shared,
    colors: {
      background: '#121211',
      surface: '#1C1B19',
      surfaceSoft: '#24231F',
      surfaceHigh: '#302E29',
      statSurface: '#191A17',
      waterSurface: '#172331',
      fertilizerSurface: '#24211E',
      harvestSurface: '#2B241B',
      successSurface: '#1B2419',
      errorSurface: '#2B1E1B',
      text: '#F5F1E8',
      textMuted: '#C5BFB2',
      primary: '#95D184',
      primaryStrong: '#B2E7A2',
      onPrimary: '#102B0D',
      secondary: '#CDB982',
      secondaryContainer: '#4C442C',
      brown: '#C9A58E',
      beige: '#2B2822',
      water: '#8EBBFF',
      sun: '#F2C461',
      harvest: '#F2A763',
      success: '#95D184',
      warning: '#F2C461',
      error: '#FFB4AB',
      info: '#8EBBFF',
      border: '#3A362F',
      shadow: '#000000',
    },
  },
  skyLight: {
    id: 'skyLight',
    name: 'Sky',
    mode: 'light',
    ...shared,
    colors: {
      background: '#F7FAFC',
      surface: '#FFFFFF',
      surfaceSoft: '#EEF6FD',
      surfaceHigh: '#DCECF9',
      statSurface: '#FFFFFF',
      waterSurface: '#E2F2FF',
      fertilizerSurface: '#EEF1F5',
      harvestSurface: '#FFF3DC',
      successSurface: '#EAF7EC',
      errorSurface: '#FFE8E8',
      text: '#162029',
      textMuted: '#586672',
      primary: '#1976D2',
      primaryStrong: '#0759A5',
      onPrimary: '#FFFFFF',
      secondary: '#64B5F6',
      secondaryContainer: '#DCEEFF',
      brown: '#7B5A42',
      beige: '#F3F7FA',
      water: '#0B7DD8',
      sun: '#F3B236',
      harvest: '#E07A20',
      success: '#2E7D32',
      warning: '#A86200',
      error: '#BA1A1A',
      info: '#1976D2',
      border: '#D9E5EE',
      shadow: '#000000',
    },
  },
  skyDark: {
    id: 'skyDark',
    name: 'Sky',
    mode: 'dark',
    ...shared,
    colors: {
      background: '#101418',
      surface: '#181D22',
      surfaceSoft: '#202830',
      surfaceHigh: '#2A3440',
      statSurface: '#161D23',
      waterSurface: '#172536',
      fertilizerSurface: '#20242A',
      harvestSurface: '#2A2117',
      successSurface: '#17251C',
      errorSurface: '#2A1B1B',
      text: '#EDF3F8',
      textMuted: '#B8C3CC',
      primary: '#7AB8FF',
      primaryStrong: '#A8D1FF',
      onPrimary: '#061D34',
      secondary: '#8CC8FF',
      secondaryContainer: '#214A70',
      brown: '#D0B49D',
      beige: '#252A2F',
      water: '#8CC8FF',
      sun: '#FFD166',
      harvest: '#FFB36D',
      success: '#7EDC82',
      warning: '#FFD166',
      error: '#FFB4AB',
      info: '#8CC8FF',
      border: '#33404A',
      shadow: '#000000',
    },
  },
  berryLight: {
    id: 'berryLight',
    name: 'Berry',
    mode: 'light',
    ...shared,
    colors: {
      background: '#FFF8FB',
      surface: '#FFFFFF',
      surfaceSoft: '#FBEFF5',
      surfaceHigh: '#F3DCE9',
      statSurface: '#FFFFFF',
      waterSurface: '#EAF3FF',
      fertilizerSurface: '#F4E9EA',
      harvestSurface: '#FFF0DE',
      successSurface: '#EDF8EF',
      errorSurface: '#FFE8E8',
      text: '#25151C',
      textMuted: '#6A5861',
      primary: '#C2185B',
      primaryStrong: '#8E1242',
      onPrimary: '#FFFFFF',
      secondary: '#F06292',
      secondaryContainer: '#FFD6E5',
      brown: '#795548',
      beige: '#FFF1F6',
      water: '#1976D2',
      sun: '#F6B73C',
      harvest: '#EF7D22',
      success: '#2E7D32',
      warning: '#B26A00',
      error: '#BA1A1A',
      info: '#1976D2',
      border: '#EAD8E0',
      shadow: '#000000',
    },
  },
  berryDark: {
    id: 'berryDark',
    name: 'Berry',
    mode: 'dark',
    ...shared,
    colors: {
      background: '#151015',
      surface: '#211821',
      surfaceSoft: '#2A202A',
      surfaceHigh: '#392B38',
      statSurface: '#1D161D',
      waterSurface: '#172331',
      fertilizerSurface: '#2A2022',
      harvestSurface: '#2B2119',
      successSurface: '#1A251C',
      errorSurface: '#2C1B22',
      text: '#F7EEF4',
      textMuted: '#C8B7C2',
      primary: '#FF8AB8',
      primaryStrong: '#FFB0CE',
      onPrimary: '#3A051D',
      secondary: '#E5A0BE',
      secondaryContainer: '#68324A',
      brown: '#D0B09E',
      beige: '#2C242A',
      water: '#8AB8FF',
      sun: '#FFD166',
      harvest: '#FFB36D',
      success: '#8ADE8F',
      warning: '#FFD166',
      error: '#FFB4AB',
      info: '#8AB8FF',
      border: '#443642',
      shadow: '#000000',
    },
  },
  citrusLight: {
    id: 'citrusLight',
    name: 'Citrus',
    mode: 'light',
    ...shared,
    colors: {
      background: '#FFFBF0',
      surface: '#FFFFFF',
      surfaceSoft: '#FFF4D8',
      surfaceHigh: '#FFE6A8',
      statSurface: '#FFFFFF',
      waterSurface: '#E7F4FF',
      fertilizerSurface: '#F4E9DC',
      harvestSurface: '#FFE8BD',
      successSurface: '#EEF8E8',
      errorSurface: '#FFE8E4',
      text: '#241A08',
      textMuted: '#665B46',
      primary: '#F28C00',
      primaryStrong: '#A95E00',
      onPrimary: '#FFFFFF',
      secondary: '#FFB300',
      secondaryContainer: '#FFE49B',
      brown: '#8A5A32',
      beige: '#FFF2D5',
      water: '#2F80B7',
      sun: '#F2B705',
      harvest: '#E56D1F',
      success: '#3F7D3A',
      warning: '#A86200',
      error: '#B3261E',
      info: '#2F80B7',
      border: '#E8D8B6',
      shadow: '#000000',
    },
  },
  citrusDark: {
    id: 'citrusDark',
    name: 'Citrus',
    mode: 'dark',
    ...shared,
    colors: {
      background: '#14120E',
      surface: '#201D17',
      surfaceSoft: '#29251B',
      surfaceHigh: '#372F20',
      statSurface: '#1B1812',
      waterSurface: '#172331',
      fertilizerSurface: '#282119',
      harvestSurface: '#332512',
      successSurface: '#1D2619',
      errorSurface: '#2B1E1B',
      text: '#F7F0E1',
      textMuted: '#C8BCA5',
      primary: '#FFC35A',
      primaryStrong: '#FFD88C',
      onPrimary: '#3A2300',
      secondary: '#DDB86A',
      secondaryContainer: '#5A431E',
      brown: '#D1A77E',
      beige: '#2D2619',
      water: '#8EBBFF',
      sun: '#FFD166',
      harvest: '#FFB36D',
      success: '#95D184',
      warning: '#FFD166',
      error: '#FFB4AB',
      info: '#8EBBFF',
      border: '#443A2A',
      shadow: '#000000',
    },
  },
  tealLight: {
    id: 'tealLight',
    name: 'Teal',
    mode: 'light',
    ...shared,
    colors: {
      background: '#F5FBF8',
      surface: '#FFFFFF',
      surfaceSoft: '#EAF6F2',
      surfaceHigh: '#D6ECE5',
      statSurface: '#FFFFFF',
      waterSurface: '#DFF4F8',
      fertilizerSurface: '#EEF0EA',
      harvestSurface: '#FFF0D8',
      successSurface: '#E6F7EF',
      errorSurface: '#FFE8E8',
      text: '#10201B',
      textMuted: '#536760',
      primary: '#009688',
      primaryStrong: '#006B60',
      onPrimary: '#FFFFFF',
      secondary: '#4DB6AC',
      secondaryContainer: '#CDEFEA',
      brown: '#795548',
      beige: '#F1F6EE',
      water: '#1976D2',
      sun: '#F6B73C',
      harvest: '#EF7D22',
      success: '#2E7D32',
      warning: '#B26A00',
      error: '#BA1A1A',
      info: '#1976D2',
      border: '#D4E6DF',
      shadow: '#000000',
    },
  },
  tealDark: {
    id: 'tealDark',
    name: 'Teal',
    mode: 'dark',
    ...shared,
    colors: {
      background: '#0F1514',
      surface: '#17201E',
      surfaceSoft: '#1E2A28',
      surfaceHigh: '#293735',
      statSurface: '#151D1B',
      waterSurface: '#162B31',
      fertilizerSurface: '#23251E',
      harvestSurface: '#2A2117',
      successSurface: '#17261F',
      errorSurface: '#2A1B1B',
      text: '#ECF5F2',
      textMuted: '#B3C4BE',
      primary: '#6DDDD2',
      primaryStrong: '#99EFE7',
      onPrimary: '#003733',
      secondary: '#83CFC7',
      secondaryContainer: '#214F49',
      brown: '#D1B0A0',
      beige: '#242A26',
      water: '#8AB8FF',
      sun: '#FFD166',
      harvest: '#FFB36D',
      success: '#7EDC82',
      warning: '#FFD166',
      error: '#FFB4AB',
      info: '#8AB8FF',
      border: '#334542',
      shadow: '#000000',
    },
  },
};

themes.roseLight = {
  ...themes.berryLight,
  id: 'roseLight',
  name: 'Rose',
  colors: {
    ...themes.berryLight.colors,
    primary: '#E11D48',
    primaryStrong: '#9F1239',
    secondary: '#FB7185',
    secondaryContainer: '#FFE4EA',
    beige: '#FFF1F4',
  },
};

themes.roseDark = {
  ...themes.berryDark,
  id: 'roseDark',
  name: 'Rose',
  colors: {
    ...themes.berryDark.colors,
    primary: '#FB7185',
    primaryStrong: '#FDA4AF',
    secondary: '#F0A4B4',
    secondaryContainer: '#6F2636',
    beige: '#2B2226',
  },
};

themes.mintLight = {
  ...themes.tealLight,
  id: 'mintLight',
  name: 'Mint',
  colors: {
    ...themes.tealLight.colors,
    primary: '#16A34A',
    primaryStrong: '#15803D',
    secondary: '#86EFAC',
    secondaryContainer: '#DCFCE7',
    beige: '#F0FDF4',
  },
};

themes.mintDark = {
  ...themes.tealDark,
  id: 'mintDark',
  name: 'Mint',
  colors: {
    ...themes.tealDark.colors,
    primary: '#86EFAC',
    primaryStrong: '#BBF7D0',
    secondary: '#74D99F',
    secondaryContainer: '#1F5D38',
    beige: '#18231B',
  },
};

themes.indigoLight = {
  ...themes.skyLight,
  id: 'indigoLight',
  name: 'Indigo',
  colors: {
    ...themes.skyLight.colors,
    primary: '#4F46E5',
    primaryStrong: '#3730A3',
    secondary: '#818CF8',
    secondaryContainer: '#E0E7FF',
    beige: '#F5F3FF',
  },
};

themes.indigoDark = {
  ...themes.skyDark,
  id: 'indigoDark',
  name: 'Indigo',
  colors: {
    ...themes.skyDark.colors,
    primary: '#A5B4FC',
    primaryStrong: '#C7D2FE',
    secondary: '#A78BFA',
    secondaryContainer: '#43306F',
    beige: '#1D1B2B',
  },
};

themes.oceanLight = {
  ...themes.skyLight,
  id: 'oceanLight',
  name: 'Ocean',
  colors: {
    ...themes.skyLight.colors,
    primary: '#0284C7',
    primaryStrong: '#075985',
    secondary: '#22D3EE',
    secondaryContainer: '#CFFAFE',
    water: '#0284C7',
    info: '#0284C7',
    beige: '#ECFEFF',
  },
};

themes.oceanDark = {
  ...themes.skyDark,
  id: 'oceanDark',
  name: 'Ocean',
  colors: {
    ...themes.skyDark.colors,
    primary: '#67E8F9',
    primaryStrong: '#A5F3FC',
    secondary: '#38BDF8',
    secondaryContainer: '#164E63',
    water: '#67E8F9',
    info: '#67E8F9',
    beige: '#14262B',
  },
};

themes.orchidLight = {
  ...themes.berryLight,
  id: 'orchidLight',
  name: 'Orchid',
  colors: {
    ...themes.berryLight.colors,
    primary: '#9333EA',
    primaryStrong: '#6B21A8',
    secondary: '#C084FC',
    secondaryContainer: '#F3E8FF',
    beige: '#FAF5FF',
  },
};

themes.orchidDark = {
  ...themes.berryDark,
  id: 'orchidDark',
  name: 'Orchid',
  colors: {
    ...themes.berryDark.colors,
    primary: '#D8B4FE',
    primaryStrong: '#E9D5FF',
    secondary: '#C084FC',
    secondaryContainer: '#581C87',
    beige: '#25182F',
  },
};

themes.coralLight = {
  ...themes.roseLight,
  id: 'coralLight',
  name: 'Coral',
  colors: {
    ...themes.roseLight.colors,
    primary: '#F43F5E',
    primaryStrong: '#BE123C',
    secondary: '#FDA4AF',
    secondaryContainer: '#FFE4E6',
    beige: '#FFF1F2',
  },
};

themes.coralDark = {
  ...themes.roseDark,
  id: 'coralDark',
  name: 'Coral',
  colors: {
    ...themes.roseDark.colors,
    primary: '#FDA4AF',
    primaryStrong: '#FFE4E6',
    secondary: '#FB7185',
    secondaryContainer: '#7F1D1D',
    beige: '#2E1C20',
  },
};

themes.jadeLight = {
  ...themes.tealLight,
  id: 'jadeLight',
  name: 'Jade',
  colors: {
    ...themes.tealLight.colors,
    primary: '#059669',
    primaryStrong: '#047857',
    secondary: '#34D399',
    secondaryContainer: '#D1FAE5',
    beige: '#ECFDF5',
  },
};

themes.jadeDark = {
  ...themes.tealDark,
  id: 'jadeDark',
  name: 'Jade',
  colors: {
    ...themes.tealDark.colors,
    primary: '#6EE7B7',
    primaryStrong: '#A7F3D0',
    secondary: '#34D399',
    secondaryContainer: '#064E3B',
    beige: '#14251F',
  },
};

themes.slateLight = {
  ...themes.skyLight,
  id: 'slateLight',
  name: 'Slate',
  colors: {
    ...themes.skyLight.colors,
    primary: '#475569',
    primaryStrong: '#334155',
    secondary: '#94A3B8',
    secondaryContainer: '#E2E8F0',
    beige: '#F8FAFC',
  },
};

themes.slateDark = {
  ...themes.skyDark,
  id: 'slateDark',
  name: 'Slate',
  colors: {
    ...themes.skyDark.colors,
    primary: '#CBD5E1',
    primaryStrong: '#F1F5F9',
    secondary: '#94A3B8',
    secondaryContainer: '#334155',
    beige: '#1E293B',
  },
};

themes.limeLight = {
  ...themes.mintLight,
  id: 'limeLight',
  name: 'Lime',
  colors: {
    ...themes.mintLight.colors,
    primary: '#65A30D',
    primaryStrong: '#4D7C0F',
    secondary: '#A3E635',
    secondaryContainer: '#ECFCCB',
    beige: '#F7FEE7',
  },
};

themes.limeDark = {
  ...themes.mintDark,
  id: 'limeDark',
  name: 'Lime',
  colors: {
    ...themes.mintDark.colors,
    primary: '#BEF264',
    primaryStrong: '#D9F99D',
    secondary: '#A3E635',
    secondaryContainer: '#365314',
    beige: '#1F2A16',
  },
};

const neutralLightSurfaces = {
  background: '#FAF9F5',
  surface: '#FFFFFF',
  surfaceSoft: '#F5F5F1',
  surfaceHigh: '#ECEDE8',
  statSurface: '#FFFFFF',
  border: '#DEE2DA',
};

const neutralDarkSurfaces = {
  background: '#101110',
  surface: '#181A18',
  surfaceSoft: '#202320',
  surfaceHigh: '#2B2E2B',
  statSurface: '#171A17',
  border: '#343834',
};

Object.values(themes).forEach((theme) => {
  Object.assign(
    theme.colors,
    theme.mode === 'dark' ? neutralDarkSurfaces : neutralLightSurfaces
  );
});

const seasonalThemeOverrides = {
  botanicalLight: {
    name: 'Spring Garden',
    colors: {
      background: '#F7FAF0',
      surface: '#FFFFFF',
      surfaceSoft: '#EEF5E7',
      surfaceHigh: '#DCEACF',
      statSurface: '#FFFFFF',
      waterSurface: '#E5F5F4',
      fertilizerSurface: '#F3EAD9',
      harvestSurface: '#FFF1D5',
      successSurface: '#E4F6E8',
      text: '#182016',
      textMuted: '#596852',
      primary: '#3B7D3C',
      primaryStrong: '#245B29',
      secondary: '#8BCF88',
      secondaryContainer: '#CFEFBE',
      brown: '#7B5B3E',
      water: '#2E8FA3',
      sun: '#E9B44C',
      harvest: '#D87524',
      border: '#D8E5CE',
      shadow: '#245B29',
    },
  },
  botanicalDark: {
    name: 'Spring Garden',
    colors: {
      background: '#10140F',
      surface: '#181D16',
      surfaceSoft: '#20281D',
      surfaceHigh: '#2B3527',
      statSurface: '#171E15',
      waterSurface: '#15282A',
      fertilizerSurface: '#282319',
      harvestSurface: '#2C2517',
      successSurface: '#172817',
      text: '#F0F5EB',
      textMuted: '#B8C6B0',
      primary: '#85D889',
      primaryStrong: '#B2ECB0',
      secondary: '#B6D49A',
      secondaryContainer: '#31592D',
      brown: '#D5B896',
      water: '#88D1D8',
      sun: '#F6D079',
      harvest: '#F3A96D',
      border: '#33402F',
      shadow: '#000000',
    },
  },
  citrusLight: {
    name: 'Summer Citrus',
    colors: {
      background: '#FFF9E8',
      surface: '#FFFFFF',
      surfaceSoft: '#FFF1C8',
      surfaceHigh: '#F8DEA0',
      statSurface: '#FFFFFF',
      waterSurface: '#E3F4F8',
      fertilizerSurface: '#F1E3CA',
      harvestSurface: '#FFE4A8',
      successSurface: '#EEF5D7',
      text: '#241B07',
      textMuted: '#675B3F',
      primary: '#D97706',
      primaryStrong: '#A14D00',
      secondary: '#F4B83F',
      secondaryContainer: '#FFE19A',
      brown: '#8A5C2F',
      water: '#227C9D',
      sun: '#F5B301',
      harvest: '#DE6B1D',
      border: '#E9D49B',
      shadow: '#7A4C00',
    },
  },
  citrusDark: {
    name: 'Summer Citrus',
    colors: {
      background: '#151208',
      surface: '#211D12',
      surfaceSoft: '#2B2618',
      surfaceHigh: '#3B321D',
      statSurface: '#1D190E',
      waterSurface: '#15272E',
      fertilizerSurface: '#2B2418',
      harvestSurface: '#382814',
      successSurface: '#202816',
      text: '#FBF0D5',
      textMuted: '#CDBE98',
      primary: '#F7C04A',
      primaryStrong: '#FFE19A',
      secondary: '#D7A64E',
      secondaryContainer: '#5A4219',
      brown: '#D5AE7A',
      water: '#83CEE0',
      sun: '#FFD166',
      harvest: '#FFB36D',
      border: '#493C24',
      shadow: '#000000',
    },
  },
  tealLight: {
    name: 'Monsoon Leaf',
    colors: {
      background: '#F0FAF6',
      surface: '#FFFFFF',
      surfaceSoft: '#E0F3EF',
      surfaceHigh: '#C7E6DE',
      statSurface: '#FFFFFF',
      waterSurface: '#D7F0F5',
      fertilizerSurface: '#E7EDE3',
      harvestSurface: '#FFF0D7',
      successSurface: '#DFF4E9',
      text: '#10211D',
      textMuted: '#506A61',
      primary: '#0F766E',
      primaryStrong: '#075E58',
      secondary: '#48BFAE',
      secondaryContainer: '#BFE9E1',
      brown: '#705C3F',
      water: '#1687A7',
      sun: '#D9AA45',
      harvest: '#D87524',
      border: '#CDE1DA',
      shadow: '#075E58',
    },
  },
  tealDark: {
    name: 'Monsoon Leaf',
    colors: {
      background: '#0D1413',
      surface: '#16201E',
      surfaceSoft: '#1D2B28',
      surfaceHigh: '#283936',
      statSurface: '#141D1B',
      waterSurface: '#142C32',
      fertilizerSurface: '#22281F',
      harvestSurface: '#2A2317',
      successSurface: '#142820',
      text: '#EAF6F2',
      textMuted: '#B0C7BF',
      primary: '#72D6C9',
      primaryStrong: '#A4EFE5',
      secondary: '#8AD3C8',
      secondaryContainer: '#24554E',
      brown: '#D2B896',
      water: '#83D6E7',
      sun: '#F2C86B',
      harvest: '#F3A96D',
      border: '#314642',
      shadow: '#000000',
    },
  },
  harvestLight: {
    name: 'Autumn Harvest',
    colors: {
      background: '#FFF8ED',
      surface: '#FFFFFF',
      surfaceSoft: '#F8EAD8',
      surfaceHigh: '#EED5B7',
      statSurface: '#FFFFFF',
      waterSurface: '#E6F1F5',
      fertilizerSurface: '#EFE0CC',
      harvestSurface: '#FFE8C2',
      successSurface: '#EAF2DC',
      text: '#251A0F',
      textMuted: '#6B5A46',
      primary: '#8A5A20',
      primaryStrong: '#633B13',
      secondary: '#C89343',
      secondaryContainer: '#EED6A5',
      brown: '#7C5131',
      water: '#2E83A3',
      sun: '#D99A2B',
      harvest: '#C65F21',
      border: '#E4CEAE',
      shadow: '#633B13',
    },
  },
  harvestDark: {
    name: 'Autumn Harvest',
    colors: {
      background: '#13110E',
      surface: '#1E1A15',
      surfaceSoft: '#282319',
      surfaceHigh: '#372E20',
      statSurface: '#1A1712',
      waterSurface: '#15242C',
      fertilizerSurface: '#282116',
      harvestSurface: '#322514',
      successSurface: '#1D2417',
      text: '#F5EEDF',
      textMuted: '#C8BCA8',
      primary: '#D7A15B',
      primaryStrong: '#F1C986',
      secondary: '#C2A16C',
      secondaryContainer: '#513B1E',
      brown: '#D4AE8A',
      water: '#89C8DD',
      sun: '#F1C76A',
      harvest: '#F2A464',
      border: '#443828',
      shadow: '#000000',
    },
  },
  skyLight: {
    name: 'Winter Greenhouse',
    colors: {
      background: '#F5F8F6',
      surface: '#FFFFFF',
      surfaceSoft: '#EAF1EF',
      surfaceHigh: '#D8E2E0',
      statSurface: '#FFFFFF',
      waterSurface: '#E0F1F6',
      fertilizerSurface: '#EAEDE6',
      harvestSurface: '#FFF2D9',
      successSurface: '#E6F2EA',
      text: '#16211F',
      textMuted: '#596865',
      primary: '#3F6F69',
      primaryStrong: '#284F4A',
      secondary: '#8BA8A4',
      secondaryContainer: '#D4E3DF',
      brown: '#75614A',
      water: '#3E88A8',
      sun: '#D7A848',
      harvest: '#D47A2B',
      border: '#D7E0DD',
      shadow: '#284F4A',
    },
  },
  skyDark: {
    name: 'Winter Greenhouse',
    colors: {
      background: '#0F1414',
      surface: '#171D1D',
      surfaceSoft: '#202929',
      surfaceHigh: '#2B3636',
      statSurface: '#151B1B',
      waterSurface: '#152A31',
      fertilizerSurface: '#222720',
      harvestSurface: '#2C2418',
      successSurface: '#17241D',
      text: '#EEF5F3',
      textMuted: '#B7C5C2',
      primary: '#9DD4CC',
      primaryStrong: '#C3EEE8',
      secondary: '#A9BFBC',
      secondaryContainer: '#315551',
      brown: '#D0B99E',
      water: '#8BD1E5',
      sun: '#F2CF77',
      harvest: '#F3A96D',
      border: '#354241',
      shadow: '#000000',
    },
  },
  roseLight: {
    name: 'Rose Bed',
    colors: {
      background: '#FFF8F7',
      surface: '#FFFFFF',
      surfaceSoft: '#FCEDEB',
      surfaceHigh: '#F4D7D2',
      statSurface: '#FFFFFF',
      waterSurface: '#EAF3F7',
      fertilizerSurface: '#F1E5DE',
      harvestSurface: '#FFF0D7',
      successSurface: '#EAF6EA',
      text: '#251817',
      textMuted: '#6A5A57',
      primary: '#B8324B',
      primaryStrong: '#842133',
      secondary: '#E07883',
      secondaryContainer: '#FFD8D9',
      brown: '#7A5A45',
      water: '#2F82A3',
      sun: '#E3AB47',
      harvest: '#D87524',
      border: '#EAD7D4',
      shadow: '#842133',
    },
  },
  roseDark: {
    name: 'Rose Bed',
    colors: {
      background: '#15100F',
      surface: '#211817',
      surfaceSoft: '#2B211F',
      surfaceHigh: '#3A2D2A',
      statSurface: '#1D1514',
      waterSurface: '#17272F',
      fertilizerSurface: '#2A231D',
      harvestSurface: '#2D2418',
      successSurface: '#17241B',
      text: '#F8EEEC',
      textMuted: '#C9B8B4',
      primary: '#F19AA2',
      primaryStrong: '#FFD1D5',
      secondary: '#DCA0A4',
      secondaryContainer: '#65323A',
      brown: '#D1B09A',
      water: '#8BC8DD',
      sun: '#F2CC73',
      harvest: '#F2A464',
      border: '#443735',
      shadow: '#000000',
    },
  },
  jadeLight: {
    name: 'Tropical Canopy',
    colors: {
      background: '#F2FAF2',
      surface: '#FFFFFF',
      surfaceSoft: '#E4F3E4',
      surfaceHigh: '#CCE5CC',
      statSurface: '#FFFFFF',
      waterSurface: '#DCF2F0',
      fertilizerSurface: '#ECE8DA',
      harvestSurface: '#FFF0C9',
      successSurface: '#DFF5DF',
      text: '#132113',
      textMuted: '#526A50',
      primary: '#1F7A45',
      primaryStrong: '#145C32',
      secondary: '#5CBF72',
      secondaryContainer: '#C7EBC9',
      brown: '#755C3F',
      water: '#148B94',
      sun: '#E3AE37',
      harvest: '#D87524',
      border: '#D1E2CF',
      shadow: '#145C32',
    },
  },
  jadeDark: {
    name: 'Tropical Canopy',
    colors: {
      background: '#0E140F',
      surface: '#172017',
      surfaceSoft: '#1F2B1F',
      surfaceHigh: '#2B3A2A',
      statSurface: '#141D14',
      waterSurface: '#132B2D',
      fertilizerSurface: '#25261D',
      harvestSurface: '#2D2416',
      successSurface: '#142817',
      text: '#EBF6EA',
      textMuted: '#B3C7B1',
      primary: '#7DDB91',
      primaryStrong: '#B5F2BF',
      secondary: '#8BCF85',
      secondaryContainer: '#2B5A32',
      brown: '#D2B996',
      water: '#7FD4D9',
      sun: '#F2CB6B',
      harvest: '#F3A96D',
      border: '#334633',
      shadow: '#000000',
    },
  },
  limeLight: {
    name: 'Herb Patch',
    colors: {
      background: '#FAFBEC',
      surface: '#FFFFFF',
      surfaceSoft: '#EEF5D4',
      surfaceHigh: '#DDEBAA',
      statSurface: '#FFFFFF',
      waterSurface: '#E2F4ED',
      fertilizerSurface: '#EDE8D7',
      harvestSurface: '#FFF0CB',
      successSurface: '#E8F6D5',
      text: '#1D220D',
      textMuted: '#626A45',
      primary: '#67911A',
      primaryStrong: '#486B10',
      secondary: '#A0C949',
      secondaryContainer: '#DDEFA7',
      brown: '#765D3B',
      water: '#288B8A',
      sun: '#D9A82F',
      harvest: '#D87524',
      border: '#DDE6BE',
      shadow: '#486B10',
    },
  },
  limeDark: {
    name: 'Herb Patch',
    colors: {
      background: '#11140B',
      surface: '#1A1F12',
      surfaceSoft: '#232B18',
      surfaceHigh: '#303A21',
      statSurface: '#171C10',
      waterSurface: '#142A27',
      fertilizerSurface: '#252419',
      harvestSurface: '#2D2416',
      successSurface: '#1B2815',
      text: '#F1F5DD',
      textMuted: '#C0C9A0',
      primary: '#BEE064',
      primaryStrong: '#DDF59A',
      secondary: '#B3D879',
      secondaryContainer: '#3F551B',
      brown: '#D2B892',
      water: '#84D2C9',
      sun: '#F2C96B',
      harvest: '#F3A96D',
      border: '#3B4429',
      shadow: '#000000',
    },
  },
};

Object.entries(seasonalThemeOverrides).forEach(([themeId, override]) => {
  Object.assign(themes[themeId], {
    name: override.name,
    colors: {
      ...themes[themeId].colors,
      ...override.colors,
    },
  });
});

const cleanDarkSurfaces = {
  background: '#020302',
  surface: '#080A08',
  surfaceSoft: '#0D100E',
  surfaceHigh: '#141814',
  statSurface: '#080A08',
  waterSurface: '#0A1216',
  fertilizerSurface: '#14110D',
  harvestSurface: '#171109',
  successSurface: '#0D100E',
  errorSurface: '#180E0E',
  beige: '#0D100E',
  secondaryContainer: '#0B100D',
  border: '#1A201C',
  shadow: '#000000',
};

Object.values(themes).forEach((theme) => {
  if (theme.mode === 'dark') {
    Object.assign(theme.colors, cleanDarkSurfaces);
  }
});

const cleanDarkAccentOverrides = {
  botanicalDark: {
    primary: '#63B96C',
    primaryStrong: '#8DCE94',
    secondary: '#7EAE7F',
    success: '#63B96C',
    onPrimary: '#07140A',
  },
  citrusDark: {
    primary: '#D99B2F',
    primaryStrong: '#EFC56E',
    secondary: '#B88A43',
    success: '#7DA96F',
    warning: '#E7B654',
    sun: '#E7B654',
    onPrimary: '#1F1300',
  },
  tealDark: {
    primary: '#5DBEB5',
    primaryStrong: '#89D7D0',
    secondary: '#72AAA4',
    success: '#66B978',
    water: '#75C4D1',
    info: '#75C4D1',
    onPrimary: '#021514',
  },
  harvestDark: {
    primary: '#C48D4F',
    primaryStrong: '#E1B875',
    secondary: '#AA8D62',
    success: '#82A96C',
    warning: '#DDB45B',
    sun: '#DDB45B',
    onPrimary: '#1D1004',
  },
  skyDark: {
    primary: '#83BDB5',
    primaryStrong: '#ACD8D2',
    secondary: '#94AAA7',
    success: '#74AD7B',
    water: '#78BED1',
    info: '#78BED1',
    onPrimary: '#061312',
  },
  roseDark: {
    primary: '#DB8790',
    primaryStrong: '#F0B2B8',
    secondary: '#C49498',
    success: '#74AD7B',
    onPrimary: '#1D070B',
  },
  jadeDark: {
    primary: '#66BD78',
    primaryStrong: '#92D69B',
    secondary: '#79B477',
    success: '#66BD78',
    water: '#72C4C9',
    info: '#72C4C9',
    onPrimary: '#061409',
  },
  limeDark: {
    primary: '#A7C958',
    primaryStrong: '#C8E281',
    secondary: '#99B86A',
    success: '#83AC68',
    onPrimary: '#111600',
  },
};

Object.entries(cleanDarkAccentOverrides).forEach(([themeId, colors]) => {
  Object.assign(themes[themeId].colors, colors);
});

export const themeFamilies = [
  {
    id: 'spring',
    label: 'Spring',
    light: 'botanicalLight',
    dark: 'botanicalDark',
    palette: ['#3B7D3C', '#8BCF88', '#F7FAF0'],
  },
  {
    id: 'summer',
    label: 'Summer',
    light: 'citrusLight',
    dark: 'citrusDark',
    palette: ['#D97706', '#F4B83F', '#FFF9E8'],
  },
  {
    id: 'monsoon',
    label: 'Monsoon',
    light: 'tealLight',
    dark: 'tealDark',
    palette: ['#0F766E', '#48BFAE', '#F0FAF6'],
  },
  {
    id: 'autumn',
    label: 'Autumn',
    light: 'harvestLight',
    dark: 'harvestDark',
    palette: ['#8A5A20', '#C89343', '#FFF8ED'],
  },
  {
    id: 'winter',
    label: 'Winter',
    light: 'skyLight',
    dark: 'skyDark',
    palette: ['#3F6F69', '#8BA8A4', '#F5F8F6'],
  },
  {
    id: 'roseBed',
    label: 'Rose Bed',
    light: 'roseLight',
    dark: 'roseDark',
    palette: ['#B8324B', '#E07883', '#FFF8F7'],
  },
  {
    id: 'tropical',
    label: 'Tropical',
    light: 'jadeLight',
    dark: 'jadeDark',
    palette: ['#1F7A45', '#5CBF72', '#F2FAF2'],
  },
  {
    id: 'herbPatch',
    label: 'Herbs',
    light: 'limeLight',
    dark: 'limeDark',
    palette: ['#67911A', '#A0C949', '#FAFBEC'],
  },
];

export const defaultThemeId = 'botanicalLight';

export function getThemeFamilyId(themeId) {
  return themeFamilies.find((family) =>
    family.light === themeId || family.dark === themeId
  )?.id || themeFamilies[0].id;
}

export function isSelectableThemeId(themeId) {
  return themeFamilies.some((family) =>
    family.light === themeId || family.dark === themeId
  );
}

export function getThemeIdForFamilyMode(familyId, mode) {
  const family = themeFamilies.find((item) => item.id === familyId) || themeFamilies[0];
  return mode === 'dark' ? family.dark : family.light;
}
