import { elevation, iconSizes, motion, radius, spacing, typography } from './tokens';

const shared = {
  spacing,
  radius,
  typography,
  elevation,
  iconSizes,
  motion,
};

export const themes = {
  botanicalLight: {
    id: 'botanicalLight',
    name: 'Botanical',
    mode: 'light',
    ...shared,
    colors: {
      background: '#FAF9F5',
      surface: '#FFFFFF',
      surfaceSoft: '#F4F4F0',
      surfaceHigh: '#E8E8E4',
      statSurface: '#FFFFFF',
      waterSurface: '#E3F2FD',
      fertilizerSurface: '#F1ECE9',
      harvestSurface: '#FFF1DD',
      successSurface: '#EAF7EC',
      errorSurface: '#FFE8E8',
      text: '#1A1C1A',
      textMuted: '#5B6558',
      primary: '#2E7D32',
      primaryStrong: '#0D631B',
      onPrimary: '#FFFFFF',
      secondary: '#81C784',
      secondaryContainer: '#ABF4AC',
      brown: '#795548',
      beige: '#F5F0E6',
      water: '#1976D2',
      sun: '#F6B73C',
      harvest: '#EF7D22',
      success: '#2E7D32',
      warning: '#B26A00',
      error: '#BA1A1A',
      info: '#1976D2',
      border: '#DCE3D7',
      shadow: '#0D631B',
    },
  },
  botanicalDark: {
    id: 'botanicalDark',
    name: 'Botanical',
    mode: 'dark',
    ...shared,
    colors: {
      background: '#111411',
      surface: '#191D19',
      surfaceSoft: '#202520',
      surfaceHigh: '#2A302A',
      statSurface: '#171C18',
      waterSurface: '#172331',
      fertilizerSurface: '#261F1B',
      harvestSurface: '#2A2117',
      successSurface: '#182419',
      errorSurface: '#2A1B1B',
      text: '#F0F3EC',
      textMuted: '#B8C0B3',
      primary: '#7EDC82',
      primaryStrong: '#9EE8A1',
      onPrimary: '#06210A',
      secondary: '#A4C3A0',
      secondaryContainer: '#2C5F34',
      brown: '#D1B0A0',
      beige: '#2A251E',
      water: '#8AB8FF',
      sun: '#FFD166',
      harvest: '#FFB36D',
      success: '#7EDC82',
      warning: '#FFD166',
      error: '#FFB4AB',
      info: '#8AB8FF',
      border: '#343B34',
      shadow: '#000000',
    },
  },
  harvestLight: {
    id: 'harvestLight',
    name: 'Harvest',
    mode: 'light',
    ...shared,
    colors: {
      background: '#FFF9F0',
      surface: '#FFFFFF',
      surfaceSoft: '#F8EFE2',
      surfaceHigh: '#F0DEC7',
      statSurface: '#FFFFFF',
      waterSurface: '#E5F2FB',
      fertilizerSurface: '#F3E8DC',
      harvestSurface: '#FFF0D8',
      successSurface: '#EAF5E4',
      errorSurface: '#FFE8E4',
      text: '#241A12',
      textMuted: '#6B5A4A',
      primary: '#3F7D3A',
      primaryStrong: '#275D28',
      onPrimary: '#FFFFFF',
      secondary: '#C7A35A',
      secondaryContainer: '#E5D8A8',
      brown: '#8A5A32',
      beige: '#F7E8CF',
      water: '#2F80B7',
      sun: '#E7A923',
      harvest: '#D9681F',
      success: '#3F7D3A',
      warning: '#A86200',
      error: '#B3261E',
      info: '#2F80B7',
      border: '#E6D4BC',
      shadow: '#8A5A32',
    },
  },
  harvestDark: {
    id: 'harvestDark',
    name: 'Harvest',
    mode: 'dark',
    ...shared,
    colors: {
      background: '#121211',
      surface: '#1C1B19',
      surfaceSoft: '#24231F',
      surfaceHigh: '#302E29',
      statSurface: '#191A17',
      waterSurface: '#172331',
      fertilizerSurface: '#24211E',
      harvestSurface: '#2B241B',
      successSurface: '#1B2419',
      errorSurface: '#2B1E1B',
      text: '#F5F1E8',
      textMuted: '#C5BFB2',
      primary: '#95D184',
      primaryStrong: '#B2E7A2',
      onPrimary: '#102B0D',
      secondary: '#CDB982',
      secondaryContainer: '#4C442C',
      brown: '#C9A58E',
      beige: '#2B2822',
      water: '#8EBBFF',
      sun: '#F2C461',
      harvest: '#F2A763',
      success: '#95D184',
      warning: '#F2C461',
      error: '#FFB4AB',
      info: '#8EBBFF',
      border: '#3A362F',
      shadow: '#000000',
    },
  },
  skyLight: {
    id: 'skyLight',
    name: 'Sky',
    mode: 'light',
    ...shared,
    colors: {
      background: '#F7FAFC',
      surface: '#FFFFFF',
      surfaceSoft: '#EEF6FD',
      surfaceHigh: '#DCECF9',
      statSurface: '#FFFFFF',
      waterSurface: '#E2F2FF',
      fertilizerSurface: '#EEF1F5',
      harvestSurface: '#FFF3DC',
      successSurface: '#EAF7EC',
      errorSurface: '#FFE8E8',
      text: '#162029',
      textMuted: '#586672',
      primary: '#1976D2',
      primaryStrong: '#0759A5',
      onPrimary: '#FFFFFF',
      secondary: '#64B5F6',
      secondaryContainer: '#DCEEFF',
      brown: '#7B5A42',
      beige: '#F3F7FA',
      water: '#0B7DD8',
      sun: '#F3B236',
      harvest: '#E07A20',
      success: '#2E7D32',
      warning: '#A86200',
      error: '#BA1A1A',
      info: '#1976D2',
      border: '#D9E5EE',
      shadow: '#000000',
    },
  },
  skyDark: {
    id: 'skyDark',
    name: 'Sky',
    mode: 'dark',
    ...shared,
    colors: {
      background: '#101418',
      surface: '#181D22',
      surfaceSoft: '#202830',
      surfaceHigh: '#2A3440',
      statSurface: '#161D23',
      waterSurface: '#172536',
      fertilizerSurface: '#20242A',
      harvestSurface: '#2A2117',
      successSurface: '#17251C',
      errorSurface: '#2A1B1B',
      text: '#EDF3F8',
      textMuted: '#B8C3CC',
      primary: '#7AB8FF',
      primaryStrong: '#A8D1FF',
      onPrimary: '#061D34',
      secondary: '#8CC8FF',
      secondaryContainer: '#214A70',
      brown: '#D0B49D',
      beige: '#252A2F',
      water: '#8CC8FF',
      sun: '#FFD166',
      harvest: '#FFB36D',
      success: '#7EDC82',
      warning: '#FFD166',
      error: '#FFB4AB',
      info: '#8CC8FF',
      border: '#33404A',
      shadow: '#000000',
    },
  },
  berryLight: {
    id: 'berryLight',
    name: 'Berry',
    mode: 'light',
    ...shared,
    colors: {
      background: '#FFF8FB',
      surface: '#FFFFFF',
      surfaceSoft: '#FBEFF5',
      surfaceHigh: '#F3DCE9',
      statSurface: '#FFFFFF',
      waterSurface: '#EAF3FF',
      fertilizerSurface: '#F4E9EA',
      harvestSurface: '#FFF0DE',
      successSurface: '#EDF8EF',
      errorSurface: '#FFE8E8',
      text: '#25151C',
      textMuted: '#6A5861',
      primary: '#C2185B',
      primaryStrong: '#8E1242',
      onPrimary: '#FFFFFF',
      secondary: '#F06292',
      secondaryContainer: '#FFD6E5',
      brown: '#795548',
      beige: '#FFF1F6',
      water: '#1976D2',
      sun: '#F6B73C',
      harvest: '#EF7D22',
      success: '#2E7D32',
      warning: '#B26A00',
      error: '#BA1A1A',
      info: '#1976D2',
      border: '#EAD8E0',
      shadow: '#000000',
    },
  },
  berryDark: {
    id: 'berryDark',
    name: 'Berry',
    mode: 'dark',
    ...shared,
    colors: {
      background: '#151015',
      surface: '#211821',
      surfaceSoft: '#2A202A',
      surfaceHigh: '#392B38',
      statSurface: '#1D161D',
      waterSurface: '#172331',
      fertilizerSurface: '#2A2022',
      harvestSurface: '#2B2119',
      successSurface: '#1A251C',
      errorSurface: '#2C1B22',
      text: '#F7EEF4',
      textMuted: '#C8B7C2',
      primary: '#FF8AB8',
      primaryStrong: '#FFB0CE',
      onPrimary: '#3A051D',
      secondary: '#E5A0BE',
      secondaryContainer: '#68324A',
      brown: '#D0B09E',
      beige: '#2C242A',
      water: '#8AB8FF',
      sun: '#FFD166',
      harvest: '#FFB36D',
      success: '#8ADE8F',
      warning: '#FFD166',
      error: '#FFB4AB',
      info: '#8AB8FF',
      border: '#443642',
      shadow: '#000000',
    },
  },
  citrusLight: {
    id: 'citrusLight',
    name: 'Citrus',
    mode: 'light',
    ...shared,
    colors: {
      background: '#FFFBF0',
      surface: '#FFFFFF',
      surfaceSoft: '#FFF4D8',
      surfaceHigh: '#FFE6A8',
      statSurface: '#FFFFFF',
      waterSurface: '#E7F4FF',
      fertilizerSurface: '#F4E9DC',
      harvestSurface: '#FFE8BD',
      successSurface: '#EEF8E8',
      errorSurface: '#FFE8E4',
      text: '#241A08',
      textMuted: '#665B46',
      primary: '#F28C00',
      primaryStrong: '#A95E00',
      onPrimary: '#FFFFFF',
      secondary: '#FFB300',
      secondaryContainer: '#FFE49B',
      brown: '#8A5A32',
      beige: '#FFF2D5',
      water: '#2F80B7',
      sun: '#F2B705',
      harvest: '#E56D1F',
      success: '#3F7D3A',
      warning: '#A86200',
      error: '#B3261E',
      info: '#2F80B7',
      border: '#E8D8B6',
      shadow: '#000000',
    },
  },
  citrusDark: {
    id: 'citrusDark',
    name: 'Citrus',
    mode: 'dark',
    ...shared,
    colors: {
      background: '#14120E',
      surface: '#201D17',
      surfaceSoft: '#29251B',
      surfaceHigh: '#372F20',
      statSurface: '#1B1812',
      waterSurface: '#172331',
      fertilizerSurface: '#282119',
      harvestSurface: '#332512',
      successSurface: '#1D2619',
      errorSurface: '#2B1E1B',
      text: '#F7F0E1',
      textMuted: '#C8BCA5',
      primary: '#FFC35A',
      primaryStrong: '#FFD88C',
      onPrimary: '#3A2300',
      secondary: '#DDB86A',
      secondaryContainer: '#5A431E',
      brown: '#D1A77E',
      beige: '#2D2619',
      water: '#8EBBFF',
      sun: '#FFD166',
      harvest: '#FFB36D',
      success: '#95D184',
      warning: '#FFD166',
      error: '#FFB4AB',
      info: '#8EBBFF',
      border: '#443A2A',
      shadow: '#000000',
    },
  },
  tealLight: {
    id: 'tealLight',
    name: 'Teal',
    mode: 'light',
    ...shared,
    colors: {
      background: '#F5FBF8',
      surface: '#FFFFFF',
      surfaceSoft: '#EAF6F2',
      surfaceHigh: '#D6ECE5',
      statSurface: '#FFFFFF',
      waterSurface: '#DFF4F8',
      fertilizerSurface: '#EEF0EA',
      harvestSurface: '#FFF0D8',
      successSurface: '#E6F7EF',
      errorSurface: '#FFE8E8',
      text: '#10201B',
      textMuted: '#536760',
      primary: '#009688',
      primaryStrong: '#006B60',
      onPrimary: '#FFFFFF',
      secondary: '#4DB6AC',
      secondaryContainer: '#CDEFEA',
      brown: '#795548',
      beige: '#F1F6EE',
      water: '#1976D2',
      sun: '#F6B73C',
      harvest: '#EF7D22',
      success: '#2E7D32',
      warning: '#B26A00',
      error: '#BA1A1A',
      info: '#1976D2',
      border: '#D4E6DF',
      shadow: '#000000',
    },
  },
  tealDark: {
    id: 'tealDark',
    name: 'Teal',
    mode: 'dark',
    ...shared,
    colors: {
      background: '#0F1514',
      surface: '#17201E',
      surfaceSoft: '#1E2A28',
      surfaceHigh: '#293735',
      statSurface: '#151D1B',
      waterSurface: '#162B31',
      fertilizerSurface: '#23251E',
      harvestSurface: '#2A2117',
      successSurface: '#17261F',
      errorSurface: '#2A1B1B',
      text: '#ECF5F2',
      textMuted: '#B3C4BE',
      primary: '#6DDDD2',
      primaryStrong: '#99EFE7',
      onPrimary: '#003733',
      secondary: '#83CFC7',
      secondaryContainer: '#214F49',
      brown: '#D1B0A0',
      beige: '#242A26',
      water: '#8AB8FF',
      sun: '#FFD166',
      harvest: '#FFB36D',
      success: '#7EDC82',
      warning: '#FFD166',
      error: '#FFB4AB',
      info: '#8AB8FF',
      border: '#334542',
      shadow: '#000000',
    },
  },
};

themes.roseLight = {
  ...themes.berryLight,
  id: 'roseLight',
  name: 'Rose',
  colors: {
    ...themes.berryLight.colors,
    primary: '#E11D48',
    primaryStrong: '#9F1239',
    secondary: '#FB7185',
    secondaryContainer: '#FFE4EA',
    beige: '#FFF1F4',
  },
};

themes.roseDark = {
  ...themes.berryDark,
  id: 'roseDark',
  name: 'Rose',
  colors: {
    ...themes.berryDark.colors,
    primary: '#FB7185',
    primaryStrong: '#FDA4AF',
    secondary: '#F0A4B4',
    secondaryContainer: '#6F2636',
    beige: '#2B2226',
  },
};

themes.mintLight = {
  ...themes.tealLight,
  id: 'mintLight',
  name: 'Mint',
  colors: {
    ...themes.tealLight.colors,
    primary: '#16A34A',
    primaryStrong: '#15803D',
    secondary: '#86EFAC',
    secondaryContainer: '#DCFCE7',
    beige: '#F0FDF4',
  },
};

themes.mintDark = {
  ...themes.tealDark,
  id: 'mintDark',
  name: 'Mint',
  colors: {
    ...themes.tealDark.colors,
    primary: '#86EFAC',
    primaryStrong: '#BBF7D0',
    secondary: '#74D99F',
    secondaryContainer: '#1F5D38',
    beige: '#18231B',
  },
};

themes.indigoLight = {
  ...themes.skyLight,
  id: 'indigoLight',
  name: 'Indigo',
  colors: {
    ...themes.skyLight.colors,
    primary: '#4F46E5',
    primaryStrong: '#3730A3',
    secondary: '#818CF8',
    secondaryContainer: '#E0E7FF',
    beige: '#F5F3FF',
  },
};

themes.indigoDark = {
  ...themes.skyDark,
  id: 'indigoDark',
  name: 'Indigo',
  colors: {
    ...themes.skyDark.colors,
    primary: '#A5B4FC',
    primaryStrong: '#C7D2FE',
    secondary: '#A78BFA',
    secondaryContainer: '#43306F',
    beige: '#1D1B2B',
  },
};

themes.oceanLight = {
  ...themes.skyLight,
  id: 'oceanLight',
  name: 'Ocean',
  colors: {
    ...themes.skyLight.colors,
    primary: '#0284C7',
    primaryStrong: '#075985',
    secondary: '#22D3EE',
    secondaryContainer: '#CFFAFE',
    water: '#0284C7',
    info: '#0284C7',
    beige: '#ECFEFF',
  },
};

themes.oceanDark = {
  ...themes.skyDark,
  id: 'oceanDark',
  name: 'Ocean',
  colors: {
    ...themes.skyDark.colors,
    primary: '#67E8F9',
    primaryStrong: '#A5F3FC',
    secondary: '#38BDF8',
    secondaryContainer: '#164E63',
    water: '#67E8F9',
    info: '#67E8F9',
    beige: '#14262B',
  },
};

themes.orchidLight = {
  ...themes.berryLight,
  id: 'orchidLight',
  name: 'Orchid',
  colors: {
    ...themes.berryLight.colors,
    primary: '#9333EA',
    primaryStrong: '#6B21A8',
    secondary: '#C084FC',
    secondaryContainer: '#F3E8FF',
    beige: '#FAF5FF',
  },
};

themes.orchidDark = {
  ...themes.berryDark,
  id: 'orchidDark',
  name: 'Orchid',
  colors: {
    ...themes.berryDark.colors,
    primary: '#D8B4FE',
    primaryStrong: '#E9D5FF',
    secondary: '#C084FC',
    secondaryContainer: '#581C87',
    beige: '#25182F',
  },
};

themes.coralLight = {
  ...themes.roseLight,
  id: 'coralLight',
  name: 'Coral',
  colors: {
    ...themes.roseLight.colors,
    primary: '#F43F5E',
    primaryStrong: '#BE123C',
    secondary: '#FDA4AF',
    secondaryContainer: '#FFE4E6',
    beige: '#FFF1F2',
  },
};

themes.coralDark = {
  ...themes.roseDark,
  id: 'coralDark',
  name: 'Coral',
  colors: {
    ...themes.roseDark.colors,
    primary: '#FDA4AF',
    primaryStrong: '#FFE4E6',
    secondary: '#FB7185',
    secondaryContainer: '#7F1D1D',
    beige: '#2E1C20',
  },
};

themes.jadeLight = {
  ...themes.tealLight,
  id: 'jadeLight',
  name: 'Jade',
  colors: {
    ...themes.tealLight.colors,
    primary: '#059669',
    primaryStrong: '#047857',
    secondary: '#34D399',
    secondaryContainer: '#D1FAE5',
    beige: '#ECFDF5',
  },
};

themes.jadeDark = {
  ...themes.tealDark,
  id: 'jadeDark',
  name: 'Jade',
  colors: {
    ...themes.tealDark.colors,
    primary: '#6EE7B7',
    primaryStrong: '#A7F3D0',
    secondary: '#34D399',
    secondaryContainer: '#064E3B',
    beige: '#14251F',
  },
};

themes.slateLight = {
  ...themes.skyLight,
  id: 'slateLight',
  name: 'Slate',
  colors: {
    ...themes.skyLight.colors,
    primary: '#475569',
    primaryStrong: '#334155',
    secondary: '#94A3B8',
    secondaryContainer: '#E2E8F0',
    beige: '#F8FAFC',
  },
};

themes.slateDark = {
  ...themes.skyDark,
  id: 'slateDark',
  name: 'Slate',
  colors: {
    ...themes.skyDark.colors,
    primary: '#CBD5E1',
    primaryStrong: '#F1F5F9',
    secondary: '#94A3B8',
    secondaryContainer: '#334155',
    beige: '#1E293B',
  },
};

themes.limeLight = {
  ...themes.mintLight,
  id: 'limeLight',
  name: 'Lime',
  colors: {
    ...themes.mintLight.colors,
    primary: '#65A30D',
    primaryStrong: '#4D7C0F',
    secondary: '#A3E635',
    secondaryContainer: '#ECFCCB',
    beige: '#F7FEE7',
  },
};

themes.limeDark = {
  ...themes.mintDark,
  id: 'limeDark',
  name: 'Lime',
  colors: {
    ...themes.mintDark.colors,
    primary: '#BEF264',
    primaryStrong: '#D9F99D',
    secondary: '#A3E635',
    secondaryContainer: '#365314',
    beige: '#1F2A16',
  },
};

const neutralLightSurfaces = {
  background: '#FAF9F5',
  surface: '#FFFFFF',
  surfaceSoft: '#F5F5F1',
  surfaceHigh: '#ECEDE8',
  statSurface: '#FFFFFF',
  border: '#DEE2DA',
};

const neutralDarkSurfaces = {
  background: '#101110',
  surface: '#181A18',
  surfaceSoft: '#202320',
  surfaceHigh: '#2B2E2B',
  statSurface: '#171A17',
  border: '#343834',
};

Object.values(themes).forEach((theme) => {
  Object.assign(
    theme.colors,
    theme.mode === 'dark' ? neutralDarkSurfaces : neutralLightSurfaces
  );
});

export const themeFamilies = [
  {
    id: 'botanical',
    label: 'Botanical',
    light: 'botanicalLight',
    dark: 'botanicalDark',
    palette: ['#2E7D32', '#8CCB9B', '#EEF4EC'],
  },
  {
    id: 'sky',
    label: 'Sky',
    light: 'skyLight',
    dark: 'skyDark',
    palette: ['#2563EB', '#38BDF8', '#EEF6FD'],
  },
  {
    id: 'berry',
    label: 'Berry',
    light: 'berryLight',
    dark: 'berryDark',
    palette: ['#7C3AED', '#A78BFA', '#F1ECFF'],
  },
  {
    id: 'rose',
    label: 'Rose',
    light: 'roseLight',
    dark: 'roseDark',
    palette: ['#E11D48', '#FB7185', '#FFF1F4'],
  },
  {
    id: 'harvest',
    label: 'Harvest',
    light: 'harvestLight',
    dark: 'harvestDark',
    palette: ['#C75A00', '#F59E0B', '#FFF1D6'],
  },
  {
    id: 'teal',
    label: 'Teal',
    light: 'tealLight',
    dark: 'tealDark',
    palette: ['#0F766E', '#2DD4BF', '#E6FFFA'],
  },
  {
    id: 'citrus',
    label: 'Citrus',
    light: 'citrusLight',
    dark: 'citrusDark',
    palette: ['#F28C00', '#FACC15', '#FFF7D6'],
  },
  {
    id: 'mint',
    label: 'Mint',
    light: 'mintLight',
    dark: 'mintDark',
    palette: ['#16A34A', '#86EFAC', '#F0FDF4'],
  },
  {
    id: 'indigo',
    label: 'Indigo',
    light: 'indigoLight',
    dark: 'indigoDark',
    palette: ['#4F46E5', '#A78BFA', '#F5F3FF'],
  },
  {
    id: 'ocean',
    label: 'Ocean',
    light: 'oceanLight',
    dark: 'oceanDark',
    palette: ['#0284C7', '#22D3EE', '#ECFEFF'],
  },
  {
    id: 'orchid',
    label: 'Orchid',
    light: 'orchidLight',
    dark: 'orchidDark',
    palette: ['#9333EA', '#C084FC', '#FAF5FF'],
  },
  {
    id: 'coral',
    label: 'Coral',
    light: 'coralLight',
    dark: 'coralDark',
    palette: ['#F43F5E', '#FDA4AF', '#FFF1F2'],
  },
  {
    id: 'jade',
    label: 'Jade',
    light: 'jadeLight',
    dark: 'jadeDark',
    palette: ['#059669', '#34D399', '#ECFDF5'],
  },
  {
    id: 'slate',
    label: 'Slate',
    light: 'slateLight',
    dark: 'slateDark',
    palette: ['#475569', '#94A3B8', '#F8FAFC'],
  },
  {
    id: 'lime',
    label: 'Lime',
    light: 'limeLight',
    dark: 'limeDark',
    palette: ['#65A30D', '#A3E635', '#F7FEE7'],
  },
];

export const defaultThemeId = 'botanicalLight';

export function getThemeFamilyId(themeId) {
  return themeFamilies.find((family) =>
    family.light === themeId || family.dark === themeId
  )?.id || themeFamilies[0].id;
}

export function getThemeIdForFamilyMode(familyId, mode) {
  const family = themeFamilies.find((item) => item.id === familyId) || themeFamilies[0];
  return mode === 'dark' ? family.dark : family.light;
}
