import { elevation, iconSizes, motion, radius, spacing, typography } from './tokens';

const shared = {
  spacing,
  radius,
  typography,
  elevation,
  iconSizes,
  motion,
};

export const themes = {
  botanicalLight: {
    id: 'botanicalLight',
    name: 'Botanical',
    mode: 'light',
    ...shared,
    colors: {
      background: '#FAF9F5',
      surface: '#FFFFFF',
      surfaceSoft: '#F4F4F0',
      surfaceHigh: '#E8E8E4',
      text: '#1A1C1A',
      textMuted: '#5B6558',
      primary: '#2E7D32',
      primaryStrong: '#0D631B',
      onPrimary: '#FFFFFF',
      secondary: '#81C784',
      secondaryContainer: '#ABF4AC',
      brown: '#795548',
      beige: '#F5F0E6',
      water: '#1976D2',
      sun: '#F6B73C',
      harvest: '#EF7D22',
      success: '#2E7D32',
      warning: '#B26A00',
      error: '#BA1A1A',
      info: '#1976D2',
      border: '#DCE3D7',
      shadow: '#0D631B',
    },
  },
  botanicalDark: {
    id: 'botanicalDark',
    name: 'Botanical',
    mode: 'dark',
    ...shared,
    colors: {
      background: '#101610',
      surface: '#182018',
      surfaceSoft: '#202B20',
      surfaceHigh: '#2A3729',
      text: '#EEF4EA',
      textMuted: '#B9C7B4',
      primary: '#88D982',
      primaryStrong: '#A3F69C',
      onPrimary: '#06220A',
      secondary: '#90D792',
      secondaryContainer: '#2E7238',
      brown: '#D7B8A8',
      beige: '#2B261E',
      water: '#8AB4F8',
      sun: '#FFD166',
      harvest: '#FFB06A',
      success: '#88D982',
      warning: '#FFD166',
      error: '#FFB4AB',
      info: '#8AB4F8',
      border: '#394936',
      shadow: '#000000',
    },
  },
  harvestLight: {
    id: 'harvestLight',
    name: 'Harvest',
    mode: 'light',
    ...shared,
    colors: {
      background: '#FFF9F0',
      surface: '#FFFFFF',
      surfaceSoft: '#F8EFE2',
      surfaceHigh: '#F0DEC7',
      text: '#241A12',
      textMuted: '#6B5A4A',
      primary: '#3F7D3A',
      primaryStrong: '#275D28',
      onPrimary: '#FFFFFF',
      secondary: '#C7A35A',
      secondaryContainer: '#E5D8A8',
      brown: '#8A5A32',
      beige: '#F7E8CF',
      water: '#2F80B7',
      sun: '#E7A923',
      harvest: '#D9681F',
      success: '#3F7D3A',
      warning: '#A86200',
      error: '#B3261E',
      info: '#2F80B7',
      border: '#E6D4BC',
      shadow: '#8A5A32',
    },
  },
  harvestDark: {
    id: 'harvestDark',
    name: 'Harvest',
    mode: 'dark',
    ...shared,
    colors: {
      background: '#17120D',
      surface: '#211A13',
      surfaceSoft: '#2C2218',
      surfaceHigh: '#392C1F',
      text: '#FFF3E4',
      textMuted: '#D8C2A7',
      primary: '#9CD28B',
      primaryStrong: '#BCEAA9',
      onPrimary: '#123511',
      secondary: '#E0BD72',
      secondaryContainer: '#5C4C25',
      brown: '#E2B98E',
      beige: '#332719',
      water: '#90CAF9',
      sun: '#FFD36A',
      harvest: '#FFAD66',
      success: '#9CD28B',
      warning: '#FFD36A',
      error: '#FFB4AB',
      info: '#90CAF9',
      border: '#4B3928',
      shadow: '#000000',
    },
  },
};

export const themeChoices = [
  { label: 'Botanical Light', value: 'botanicalLight' },
  { label: 'Botanical Dark', value: 'botanicalDark' },
  { label: 'Harvest Light', value: 'harvestLight' },
  { label: 'Harvest Dark', value: 'harvestDark' },
];

export const defaultThemeId = 'botanicalLight';
